# Generated by Django 4.1.7 on 2023-04-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='is_phD',
        ),
    ]
